### ISSUE TITLE
Plugin prevents uploads

### ISSUE THREAD

**Issue by ifeldshteyn** [mattermost/mattermost-plugin-antivirus#29] opened 2021-04-20 01:10 UTC
Hi, 

We've just upgraded to MM server 5.34.2 and the 0.1.2 AV plugin seems to no longer work. Whenever we paste an image instead of getting an error that it failed to scan we get this eror in the GUI "**Your proposed upload is smaller than the minimum allowed object size**"

`2021-04-19T21:00:09.991-0400    error   mlog/log.go:232 Unable to write the file.       {"path": "/api/v4/files", "request_id": "6q7qmedp7i8gpdhrci5o1w67ic", "ip_addr": "172.19.36.111", "user_id": "dm3j7nq873ga3qrch7ssujyqee", "method": "POST", "err_where": "WriteFile", "http_code": 500, "err_details": "unable write the data in the file 20210419/teams/noteam/channels/6qor8rxzjbyb7r4vsd35fpr118e/users/ddfdm3j7nq819ga45sdfs23sujyqee/gr314yardnsdf213xyzyjodugdfd1fw/Drawing1.jpg.tmp: Your proposed upload is smaller than the minimum allowed object size."}`

If we disable the plugin, the error goes away. The AV server we work with is up and responding (and was working fine under the previous version 5.29.1). 

On enabling the plugin we get this error (not sure if it is a problem). 

`2021-04-19T20:59:38.070-0400    error   app/file.go:1203        creating mini preview failed    {"error": "failed to save FileInfo: Error 1062: Duplicate entry '51p8fzeegaujfe7me5t413hnbj3bc' for key 'PRIMARY'", "errorVerbose": "Error 1062: Duplicate entry '51p8fzeegaujfe7me5t413hnbj3bc' for key 'PRIMARY'\nfailed to save FileInfo\ngithub.com/mattermost/mattermost-server/v5/store/sqlstore.SqlFileInfoStore.Upsert\n\tgithub.com/mattermost/mattermost-server/v5/store/sqlstore/file_info_store.go:129\ngithub.com/mattermost/mattermost-server/v5/store/retrylayer.(*RetryLayerFileInfoStore).Upsert\n\tgithub.com/mattermost/mattermost-server/v5/store/retrylayer/retrylayer.go:3463\ngithub.com/mattermost/mattermost-server/v5/store/timerlayer.(*TimerLayerFileInfoStore).Upsert\n\tgithub.com/mattermost/mattermost-server/v5/store/timerlayer/timerlayer.go:2963\ngithub.com/mattermost/mattermost-server/v5/app.(*App).generateMiniPreview\n\tgithub.com/mattermost/mattermost-server/v5/app/file.go:1202\ngithub.com/mattermost/mattermost-server/v5/app.(*App).GetFileInfo\n\tgithub.com/mattermost/mattermost-server/v5/app/file.go:1235\ngithub.com/mattermost/mattermost-server/v5/api4.getFilePreview\n\tgithub.com/mattermost/mattermost-server/v5/api4/file.go:584\ngithub.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP\n\tgithub.com/mattermost/mattermost-server/v5/web/handlers.go:279\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1\n\tgithub.com/NYTimes/gziphandler@v1.1.1/gzip.go:337\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/rs/cors.(*Cors).Handler.func1\n\tgithub.com/rs/cors@v1.7.0/cors.go:219\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2843\nnet/http.(*conn).serve\n\tnet/http/server.go:1925\nruntime.goexit\n\truntime/asm_amd64.s:1374"}`

I am guessing there is some new functionality that makes this plugin no longer compatible with the latest MM version? if you can take a look we'd greatly appreciate it .

Thanks,
Ilya

**Comment by ifeldshteyn** [comment] 2021-08-06 14:46
Hi, was just wondering if there was any update on this? Thank you!

**Comment by hanzei** [comment] 2021-08-19 20:18
@deepakdemiwal Did someone took a look at this issue?

**Comment by deepakdemiwal** [comment] 2021-08-20 03:24
@hanzei Yes @maisnamrajusingh tried to reproduce it, but could not and we moved it in pending validation card.

**Comment by maisnamrajusingh** [comment] 2021-08-23 15:35
@ifeldshteyn I tried to see if I could replicate the issue. May I know how you installed the antivirus and also your os version ?

**Comment by hanzei** [comment] 2021-10-06 17:35
Closing this as can't reproduce

**Closed as completed by hanzei** 2021-10-06 17:35 UTC
Labels: Help Wanted, Hacktoberfest, Type/Bug
